version: "3.9"
services:
  browser:
    build:
      context: .
      dockerfile: Dockerfile
    image: pBrowser
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GUACAMOLE_HOSTNAME: localhost
      GUACAMOLE_PORT: 8080
      GUACAMOLE_USERNAME: admin
      GUACAMOLE_PASSWORD: password
